source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/plug-config/polyglot.vim
source $HOME/.config/nvim/plug-config/NERDTree.vim
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/vim-plug/plugs.vim
source $HOME/.config/nvim/themes/autoformat.vim
source $HOME/.config/nvim/themes/themes.vim
"source $HOME/.config/nvim/cp.vim
